/*
 * maquina_de_estados.h
 *
 *  Created on: 13/09/2014
 *      Author: Usuario
 */

#ifndef MAQUINA_DE_ESTADOS_H_
#define MAQUINA_DE_ESTADOS_H_


enum e_MAQUINA_ESTADO
{
	MAQUINA_ESTADO_RESET,
	MAQUINA_ESTADO_1,
	E_MAX_MAQUINA_ESTADO
};

enum e_MAQUINA_ESTADO_LEDS
{
	MAQUINA_ESTADO_LEDS_OFF,
	MAQUINA_ESTADO_LEDS_NONE,
	MAQUINA_ESTADO_LEDS_CHANGE,
	E_MAX_MAQUINA_ESTADO_LEDS
};

enum e_MAQUINA_ESTADO_TEC
{
	MAQUINA_ESTADO_TEC_KEY4_SUELTA,
	MAQUINA_ESTADO_TEC_KEY4_SOLTADO,
	MAQUINA_ESTADO_TEC_KEY4_APRIETA,
	MAQUINA_ESTADO_TEC_KEY4_APRETADO,
	E_MAX_MAQUINA_ESTADO_TEC
};


void Maquina_de_estados();


#endif /* MAQUINA_DE_ESTADOS_H_ */
